--[[
码上 project by Ayaka_Ago

Barcode Scanning by ZXing
https://github.com/zxing/zxing
]]

require "import"
import "mods.func"
import "Pretend"
import "mods.glob"


--checkUpdate()

this.setContentView(loadlayout({
  RelativeLayout,
  {
    RelativeLayout,
    layout_height="13%h",
    layout_alignParentTop=true;
    layout_width="fill",
    id="topBar",
    backgroundColor=0,
    elevation="1%w",
    onClick=function ()
    end,
    paddingTop=状态栏高度,
    {
      ImageView,
      src="image/left.png",
      layout_alignParentLeft=true;
      layout_height="fill",
      layout_width="8.5%h",
      onClick=function ()
        this.finish()
      end,
      padding="4%w",
      id="back",
      ColorFilter=0xff000000,
      foreground=转波纹色(0xcb5B5B5B),
    },
    {
      TextView,
      id="title",
      text="关于",
      layout_toRightOf="back",
      gravity="left|center",
      textSize="18sp",
      layout_height="fill",
      textColor=0xff444444,
    },
    {
      ImageView,
      layout_alignParentRight=true;
      layout_height="fill",
      layout_width="8.5%h",
      visibility=8,
      id="none_ic",
      padding="4%w",
      ColorFilter=0xff000000,
    },
  },
  {
    ScrollView,
    id="content",
    {
      LinearLayout,
      orientation="vertical",
      {
        RelativeLayout,
        {
          ImageView,
          src="http://image.coolapk.com/picture/2019/0103/18/1625219_1546509873_0732@1080x1920.jpg.m.jpg",
          id="top_pic",
          layout_width="fill",
          layout_height="50%h",
          scaleType="centerCrop",
          foreground=上下渐变({0x88ffffff,0xFFFAFAFA}),
        },
        {
          LinearLayout,
          orientation="vertical",
          gravity="center",
          layout_width="fill",
          paddingTop=h*0.085+状态栏高度,
          layout_height="50%h",
          {
            CardView,
            radius="17dp",
            layout_width="25%w",
            layout_gravity="center",
            layout_height="25%w",
            elevation="2.5dp",
            layout_margin="2%w",
            CardBackgroundColor=0xFF4DB6AC;--卡片背景颜色        
            {
              ImageView,
              src="icon.png",
              id="app_icon",
              layout_gravity="center",
            },
          },
          {
            TextView,
            text="轻工具箱",
            padding="4%w",
            textColor=0xff444444,
            id="app_name",
            gravity="center",
            textSize="25sp",
          },
          {
            TextView,
            text=本地版本,
            textColor=0xff444444,
            gravity="center",
            textSize="17sp",
            id="app_ver",
          },
        },
      },
      {
        LinearLayout,
        orientation="vertical",
        padding="4%w",
        {
          TextView,
          padding="4%w",
          text="应用信息",
        },
        {
          RelativeLayout,
          layout_height="8.5%h",
          onClick=function()
            checkupdate()
          end,
          foreground=转波纹色(0xcb5B5B5B),
          {
            LinearLayout,
            orientation="horizontal",
            layout_alignParentLeft=true,
            {
              ImageView,
              src="image/version.png",
              layout_height="56dp";
              layout_width="56dp";
              padding="16dp";
            },
            {
              TextView,
              text="版本状态",
              gravity="left|center",
              textSize="15sp",
              layout_height="fill",
              textColor=0xff444444,
            },
          },
          {
            TextView,
            text="正在更新......",
            layout_height="fill",
            gravity="center",
            id="version_note",
            textColor=0xFF5C5C5C,
            padding="4%w",
            layout_alignParentRight=true,
          },
        },
        {
          RelativeLayout,
          layout_height="8.5%h",
          onClick=function()
            更新日志()
          end,
          foreground=转波纹色(0xcb5B5B5B),
          {
            LinearLayout,
            orientation="horizontal",
            layout_alignParentLeft=true,
            {
              ImageView,
              src="image/clipboard.png",
              layout_height="56dp";
              layout_width="56dp";
              padding="16dp";
            },
            {
              TextView,
              text="更新日志",
              gravity="left|center",
              textSize="15sp",
              layout_height="fill",
              textColor=0xff444444,
            },
          },
          {
            TextView,
            layout_height="fill",
            gravity="center",
            textColor=0xFF5C5C5C,
            padding="4%w",
            layout_alignParentRight=true,
          },
        },
        {
          RelativeLayout,
          layout_height="8.5%h",
          onClick=function()
            协议()
          end,
          foreground=转波纹色(0xcb5B5B5B),
          {
            LinearLayout,
            orientation="horizontal",
            layout_alignParentLeft=true,
            {
              ImageView,
              src="image/assignment_turned_in.png",
              layout_height="56dp";
              layout_width="56dp";
              padding="16dp";
            },
            {
              TextView,
              text="使用协议",
              gravity="left|center",
              textSize="15sp",
              layout_height="fill",
              textColor=0xff444444,
            },
          },
          {
            TextView,
            layout_height="fill",
            gravity="center",
            textColor=0xFF5C5C5C,
            padding="4%w",
            layout_alignParentRight=true,
          },
        },

        {
          TextView,
          padding="4%w",
          text="开发相关",
        },
        {
          RelativeLayout,
          layout_height="8.5%h",
          onClick=function()
            this.newActivity("open_source")
          end,
          foreground=转波纹色(0xcb5B5B5B),
          {
            LinearLayout,
            orientation="horizontal",
            layout_alignParentLeft=true,
            {
              ImageView,
              src="image/github.png",
              layout_height="56dp";
              layout_width="56dp";
              padding="16dp";
            },
            {
              TextView,
              text="开源许可",
              gravity="left|center",
              textSize="15sp",
              layout_height="fill",
              textColor=0xff444444,
            },
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="8.5%h",
            padding="4%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          RelativeLayout,
          layout_height="8.5%h",
          onClick=function()
            this.newActivity("thanks")
          end,
          foreground=转波纹色(0xcb5B5B5B),
          {
            LinearLayout,
            orientation="horizontal",
            layout_alignParentLeft=true,
            {
              ImageView,
              src="image/people.png",
              layout_height="56dp";
              layout_width="56dp";
              padding="16dp";
            },
            {
              TextView,
              text="感谢名单",
              gravity="left|center",
              textSize="15sp",
              layout_height="fill",
              textColor=0xff444444,
            },
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="8.5%h",
            padding="4%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          RelativeLayout,
          layout_height="8.5%h",
          onClick=function()
            import "android.content.*"
            打开网页("https://wj.qq.com/s2/2741342/489f/","普通","意见反馈",nil,{"page-footer  copyright"})
            写入剪贴板(Build.MODEL)
          end,
          foreground=转波纹色(0xcb5B5B5B),
          {
            LinearLayout,
            orientation="horizontal",
            layout_alignParentLeft=true,
            {
              ImageView,
              src="image/feedback.png",
              layout_height="56dp";
              layout_width="56dp";
              padding="16dp";
            },
            {
              TextView,
              text="意见反馈",
              gravity="left|center",
              textSize="15sp",
              layout_height="fill",
              textColor=0xff444444,
            },
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="8.5%h",
            padding="4%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          TextView,
          padding="4%w",
          text="其他",
        },
        {
          RelativeLayout,
          layout_height="8.5%h",
          onClick=function()
            QQ聊天窗("2960586094")
          end,
          foreground=转波纹色(0xcb5B5B5B),
          {
            LinearLayout,
            orientation="horizontal",
            layout_alignParentLeft=true,
            {
              ImageView,
              src="image/account_circle.png",
              layout_height="56dp";
              layout_width="56dp";
              padding="16dp";
            },
            {
              TextView,
              text="联系作者",
              gravity="left|center",
              textSize="15sp",
              layout_height="fill",
              textColor=0xff444444,
            },
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="8.5%h",
            padding="4%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          RelativeLayout,
          layout_height="8.5%h",
          onClick=function()
            QQ群("879136513")
          end,
          foreground=转波纹色(0xcb5B5B5B),
          {
            LinearLayout,
            orientation="horizontal",
            layout_alignParentLeft=true,
            {
              ImageView,
              src="image/add_box.png",
              layout_height="56dp";
              layout_width="56dp";
              padding="16dp";
            },
            {
              TextView,
              text="加官方群",
              gravity="left|center",
              textSize="15sp",
              layout_height="fill",
              textColor=0xff444444,
            },
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="8.5%h",
            padding="4%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },

      },
    },
  },
}))

content.onScrollChange=function (v,u,p)
  if p>=app_icon.bottom then
    if none_ic.getVisibility()~=0 then
      none_ic.setVisibility(0)
      transColor(topBar,"backgroundColor",{topBar.getBackground().getColor(),returntheme()},350)
      transColor(back,"ColorFilter",{back.getColorFilter(),0xffffffff},350)
      transColor(title,"textColor",{title.getCurrentTextColor(),0xffffffff},350)

    end
   else
    if none_ic.getVisibility()~=8 then
      none_ic.setVisibility(8)
      transColor(topBar,"backgroundColor",{topBar.getBackground().getColor(),0},350)
      transColor(back,"ColorFilter",{back.getColorFilter(),0xff000000},350)
      transColor(title,"textColor",{title.getCurrentTextColor(),0xff444444},350)

    end
  end
end



获得版本信息()