require "import"
import "mods.glob"
import "Pretend"
import "mods.func"
name=...
packinfo = pm.getPackageInfo(name, 64)
pack = pm.getApplicationInfo(name, PackageManager.GET_META_DATA)

function onResume()
  if pcall(function ()
      --路径与名称
      安装包路径=tostring(pm.getApplicationInfo(name, 64).sourceDir)
      数据路径=tostring(pm.getApplicationInfo(name, 64).dataDir)
      apk_size.text=Formatter.formatFileSize(this,getFileSize(安装包路径))
      pt.text=安装包路径
      dt.text=数据路径
      nm.text=tostring(pm.getApplicationLabel(pack))
      pn.text=tostring(pack.packageName)
      freeze_state=tonumber(pm.getApplicationEnabledSetting(pack.packageName))
      if freeze_state==pm.COMPONENT_ENABLED_STATE_DISABLED then
        freezed_notice.setVisibility(0)
       else
        freezed_notice.setVisibility(8)
      end
      --应用图标
      ic.setImageBitmap(pack.loadIcon(pm).getBitmap())
      --版本信息
      vc.text="内部版本号 "..tostring(packinfo.versionCode)
      vn.text="版本号 "..tostring(packinfo.versionName)
      --安装时间与更新时间
      app_install.text=Calendar.getInstance().setTimeInMillis(tonumber(packinfo.firstInstallTime)).getTime().toLocaleString()
      app_update.text=Calendar.getInstance().setTimeInMillis(tonumber(packinfo.lastUpdateTime)).getTime().toLocaleString()
      --其他信息
      app_uid.text=tostring(pack.uid)
      app_prc.text=tostring(pack.processName)
      app_lc.text=tostring(getLaunchClass(name))
      app_inf.text=tostring(pack.flags)
    end) then else
    提示 ("应用信息加载失败，该应用可能已被卸载。")
    this.finish()
  end
end

this.setContentView(loadlayout ({
  LinearLayout,
  orientation="vertical",
  {
    RelativeLayout,
    layout_height="21.75%w",
    layout_width="fill",
    id="topBar",
    elevation="2dp",
    paddingTop=状态栏高度,
    backgroundColor=returntheme(),
    {
      ImageView,
      src="image/left.png",
      layout_alignParentLeft=true;
      layout_height="fill",
      layout_width="13%w",
      onClick=function ()
        this.finish()
      end,
      foreground=转波纹色(0xffffffff),
      padding="3.5%w",
      id="back",
      ColorFilter="#FFFFFFFF";
    },
    {
      TextView,
      id="title",
      text="应用信息",
      paddingRight="13%w",
      paddingLeft="3%w",
      layout_toRightOf="back",
      gravity="left|center",
      singleLine=true,
      ellipsize="end",
      textSize="18sp",
      layout_height="fill",
      layout_width="fill",
      textColor=0xffffffff,
    },
    {
      LinearLayout,
      layout_alignParentRight=true;
      orientation="horizontal",
      {
        ImageView,
        src="image/info.png",
        onClick=function ()

        end,
        foreground=转波纹色(0xcb5B5B5B),
        layout_height="fill",
        layout_width="13%w",
        visibility=8,
        padding="3.5%w",
      },
    },
  },
  {
    ScrollView,
    {
      LinearLayout,
      orientation="vertical",
      paddingBottom="3.5%w",
      {
        TextView,
        id="freezed_notice",
        layout_width="fill",
        text="该应用已被冻结",
        padding="3.5%w",
        backgroundColor=0xFFFFBABA,
        textColor=0xffff4500,
      },
      {
        RelativeLayout,
        layout_height="wrap",
        paddingTop="3.5%w",
        gravity="center",
        layout_width="fill",
        {
          LinearLayout,
          orientation="horizontal",
          layout_width="fill",
          {
            LinearLayout,
            orientation="vertical",
            layout_gravity="center",
            {
              ImageView,
              id="ic",
              layout_height="20%w",
              layout_width="20%w",
              adjustViewBounds=true,
              padding="3.5%w",
            },
            {
              TextView,
              id="app_sys",
              layout_gravity="center",
            },
          },
          {
            LinearLayout,
            orientation="vertical",
            layout_gravity="center|left",
            {
              TextView,
              textSize="16sp",
              textColor=0xff444444,
              id="nm",
              text=name,
              padding="2%w",
              textIsSelectable=true,
              paddingLeft=0,
              paddingRight="3.5%w",
            },
            {
              TextView,
              textSize="14sp",
              paddingBottom="2%w",
              textIsSelectable=true,
              paddingRight="3.5%w",
              id="vn",
            },
            {
              TextView,
              textSize="14sp",
              paddingBottom="2%w",
              textIsSelectable=true,
              paddingRight="3.5%w",
              id="vc",
            },
          },
        },
      },
      {
        LinearLayout,
        id="info_area",
        orientation="vertical",
        {
          TextView,
          textSize="14sp",
          padding="3.5%w",
          text="包名",
          paddingBottom=0,
        },
        {
          TextView,
          textSize="16sp",
          textColor=0xff444444,
          padding="3.5%w",
          id="pn",
          textIsSelectable=true,
        },
        {
          LinearLayout,
          {
            TextView,
            textSize="14sp",
            padding="3.5%w",
            text="UID",
          },
          {
            TextView,
            textSize="16sp",
            textColor=0xff444444,
            padding="3.5%w",
            id="app_uid",
            textIsSelectable=true,
          },
        },
        {
          LinearLayout,
          {
            TextView,
            textSize="14sp",
            padding="3.5%w",
            text="标志",
          },
          {
            TextView,
            textSize="16sp",
            textColor=0xff444444,
            padding="3.5%w",
            id="app_inf",
            textIsSelectable=true,
          },
        },
        {
          TextView,
          textSize="14sp",
          padding="3.5%w",
          text="数据路径",
          paddingBottom=0,
        },
        {
          TextView,
          textSize="16sp",
          textColor=0xff444444,
          padding="3.5%w",
          id="dt",
          textIsSelectable=true,
        },
        {
          TextView,
          textSize="14sp",
          padding="3.5%w",
          text="安装包路径",
          paddingBottom=0,
        },
        {
          TextView,
          textSize="16sp",
          textColor=0xff444444,
          padding="3.5%w",
          id="pt",
          textIsSelectable=true,
        },
        {
          LinearLayout,
          {
            TextView,
            textSize="14sp",
            padding="3.5%w",
            text="安装包大小",
          },
          {
            TextView,
            textSize="16sp",
            textColor=0xff444444,
            padding="3.5%w",
            id="apk_size",
            textIsSelectable=true,
          },
        },
        {
          TextView,
          textSize="14sp",
          padding="3.5%w",
          text="启动类",
          paddingBottom=0,
        },
        {
          TextView,
          textSize="16sp",
          textColor=0xff444444,
          padding="3.5%w",
          id="app_lc",
          textIsSelectable=true,
        },
        {
          TextView,
          textSize="14sp",
          padding="3.5%w",
          text="进程名",
          paddingBottom=0,
        },
        {
          TextView,
          textSize="16sp",
          textColor=0xff444444,
          padding="3.5%w",
          id="app_prc",
          textIsSelectable=true,
        },
        {
          LinearLayout,
          {
            TextView,
            textSize="14sp",
            padding="3.5%w",
            text="安装时间",
          },
          {
            TextView,
            textSize="16sp",
            textColor=0xff444444,
            padding="3.5%w",
            id="app_install",
            textIsSelectable=true,
          },
        },
        {
          LinearLayout,
          {
            TextView,
            textSize="14sp",
            padding="3.5%w",
            text="更新时间",
          },
          {
            TextView,
            textSize="16sp",
            textColor=0xff444444,
            padding="3.5%w",
            id="app_update",
            textIsSelectable=true,
          },
        },
        {
          TextView,
          padding="3.5%w",
          textColor=0xff444444,
          text="其他信息",
        },
        {
          RelativeLayout,
          layout_height="13%w",
          onClick=function()
            this.newActivity("permission",{name})
          end,
          paddingLeft="3.5%w",
          foreground=转波纹色(0xcb5B5B5B),
          {
            TextView,
            text="权限",
            gravity="left|center",
            textSize="16sp",
            layout_height="fill",
            textColor=0xff444444,
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="13%w",
            padding="3.5%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          RelativeLayout,
          layout_height="13%w",
          onClick=function()
            this.newActivity("activities",{name})
          end,
          paddingLeft="3.5%w",
          foreground=转波纹色(0xcb5B5B5B),
          {
            TextView,
            text="Activity",
            gravity="left|center",
            textSize="16sp",
            layout_height="fill",
            textColor=0xff444444,
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="13%w",
            padding="3.5%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          RelativeLayout,
          layout_height="13%w",
          onClick=function()
            this.newActivity("service",{name})
          end,
          paddingLeft="3.5%w",
          foreground=转波纹色(0xcb5B5B5B),
          {
            TextView,
            text="Service",
            gravity="left|center",
            textSize="16sp",
            layout_height="fill",
            textColor=0xff444444,
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="13%w",
            padding="3.5%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          RelativeLayout,
          layout_height="13%w",
          onClick=function()
            this.newActivity("provider",{name})
          end,
          paddingLeft="3.5%w",
          foreground=转波纹色(0xcb5B5B5B),
          {
            TextView,
            text="Provider",
            gravity="left|center",
            textSize="16sp",
            layout_height="fill",
            textColor=0xff444444,
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="13%w",
            padding="3.5%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          RelativeLayout,
          layout_height="13%w",
          onClick=function()
            this.newActivity("signature",{name})
          end,
          paddingLeft="3.5%w",
          foreground=转波纹色(0xcb5B5B5B),
          {
            TextView,
            text="签名信息",
            gravity="left|center",
            textSize="16sp",
            layout_height="fill",
            textColor=0xff444444,
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="13%w",
            padding="3.5%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
        {
          RelativeLayout,
          layout_height="13%w",
          onClick=function()
            this.newActivity("manage",{name})
          end,
          paddingLeft="3.5%w",
          foreground=转波纹色(0xcb5B5B5B),
          {
            TextView,
            text="管理",
            gravity="left|center",
            textSize="16sp",
            layout_height="fill",
            textColor=0xff444444,
          },
          {
            ImageView,
            src="image/arrow.png",
            layout_height="fill",
            layout_width="13%w",
            padding="3.5%w",
            layout_alignParentRight=true,
            rotation=-90,
          },
        },
      },
    },
  },
}))