--[[
码上 project by Ayaka_Ago

]]

require "import"
import "mods.glob"
import "mods.func"
import "Pretend"
import 'android.graphics.*'
this.setContentView(loadlayout ({
  RelativeLayout,
  {
    RelativeLayout,
    layout_height="13%h",
    BackgroundColor=returntheme();
    layout_alignParentTop=true;
    layout_width="fill",
    id="topBar",
    elevation="1%w",
    paddingTop=状态栏高度,
    {
      ImageView,
      src="image/left.png",
      layout_alignParentLeft=true;
      layout_height="fill",
      layout_width="8.5%h",
      onClick=function ()
        this.finish()
      end,
      foreground=转波纹色(0xcb5B5B5B),
      padding="4%w",
      id="back",
      colorFilter=0xfffffffd,
    },
    {
      TextView,
      text="感谢名单(排名不分先后)",
      layout_toRightOf="back",
      gravity="left|center",
      textSize="18sp",
      layout_height="fill",
      textColor=0xffffffff,
    },
    {
      ImageView,
      layout_alignParentRight=true;
      layout_height="fill",
      layout_width="8.5%h",
      padding="4%w",
      --      colorFilter=顶栏图标色,
    },
  },
  {
    ScrollView,
    layout_width="fill",
    layout_marginTop="13%h",
    {
      LinearLayout,
      layout_width="fill",
      padding="4%w",
      orientation="vertical",
      {
        TextView,
        padding="4%w",
        text="技术支持",
      },
      {
        LinearLayout,
        orientation="vertical",
        layout_height="wrap",
        layout_width="fill",
        onClick=function ()
          酷安打开app("com.pretend.appluaj")
        end,
        foreground=转波纹色(0xcb5B5B5B),
        paddingBottom="2%w",
        {
          RelativeLayout,
          padding="4%w",
          paddingLeft=0,
          layout_height="13%h",
          {
            LinearLayout,
            orientation="horizontal",
            layout_height="13%h",
            layout_width="fill",
            {
              CircleImageView,
              src="http://image.coolapk.com/apk_logo/2019/0826/19/ic_launcher-241206-o_1dj6qqlj21ls81q6u13devq71nl81c-uid-982645@500x500.png",
              layout_width="13%h",
              layout_height="fill",
            },
            {
              LinearLayout,
              orientation="vertical",
              layout_height="fill",
              gravity="center|left",
              {
                TextView,
                text="AppLua",
                textSize="18sp",
                textColor=0xff444444,
              },
              {
                TextView,
                paddingTop="1%w",
                text="Pretend",
              },
            },
          },

        },
        {
          TextView,
          textColor=0xff444444,
          textSize="15sp",
          padding="4%w",
          text=[[AppLua是一款Lua语言和java语言混合开发的编辑器，基于nirenr开源的AndroLua+。]],
        },
        {
          LinearLayout,
          orientation="horizontal",
          layout_height="4%h",
          paddingRight="4%w",
          layout_gravity="right|center",
          {
            TextView,
            gravity="center",
            text="在酷安中查看",
            textColor=returntheme(),
            textSize="14sp",
            id="bt1";
            paddingRight="1%w",
            layout_height="fill",
          },
          {
            ImageView,
            src="image/left.png",
            layout_height="fill",
            layout_width="4%h",
            colorFilter=returntheme(),
            padding="0.75%w",
            rotation=180,
          },
        },
      },
      {
        TextView,
        padding="4%w",
        text="代码参考",
      },
      {
        LinearLayout,
        orientation="vertical",
        layout_height="wrap",
        layout_width="fill",
        onClick=function ()
          浏览器打开网页("https://www.lanzous.com/i53lqkf")
        end,
        foreground=转波纹色(0xcb5B5B5B),
        paddingBottom="2%w",
        {
          RelativeLayout,
          padding="4%w",
          paddingLeft=0,
          layout_height="13%h",
          {
            LinearLayout,
            orientation="horizontal",
            layout_height="13%h",
            layout_width="fill",
            {
              CircleImageView,
              src="https://i.loli.net/2019/07/21/5d3488929426a37626.png",
              layout_width="13%h",
              layout_height="fill",
            },
            {
              LinearLayout,
              orientation="vertical",
              layout_height="fill",
              gravity="center|left",
              {
                TextView,
                text="码上",
                textSize="18sp",
                textColor=0xff444444,
              },
              {
                TextView,
                paddingTop="1%w",
                text="Ayaka_Ago",
              },
            },
          },
          {
            CircleImageView,
            layout_width="7%h",
            layout_height="fill",
            layout_alignParentRight=true,
          },
        },
        {
          TextView,
          textColor=0xff444444,
          textSize="15sp",
          padding="4%w",
          text=[[码上 ("onCode") 是一个使用 FusionApp 开发，Lua 语言编写的界面清新简约的二维码工具。使用ZXing的二维码库。

布局采用白色渐变，卡片质感的设计，给用户较好的视觉效果。]],
        },
        {
          LinearLayout,
          orientation="horizontal",
          layout_height="4%h",
          paddingRight="4%w",
          layout_gravity="right|center",
          {
            TextView,
            gravity="center",
            text="下载该APP",
            textColor=returntheme(),
            textSize="14sp",
            id="bt2";
            paddingRight="1%w",
            layout_height="fill",
          },
          {
            ImageView,
            src="image/left.png",
            layout_height="fill",
            layout_width="4%h",
            colorFilter=returntheme(),
            padding="0.75%w",
            rotation=180,
          },
        },
      },
      {
        TextView,
        padding="4%w",
        text="内容提供",
      },
      {
        LinearLayout,
        orientation="vertical",
        layout_height="wrap",
        layout_width="fill",
        onClick=function ()
          浏览器打开网页("http://free.3v.do/")
        end,
        foreground=转波纹色(0xcb5B5B5B),
        paddingBottom="2%w",
        {
          RelativeLayout,
          padding="4%w",
          paddingLeft=0,
          layout_height="13%h",
          {
            LinearLayout,
            orientation="horizontal",
            layout_height="13%h",
            layout_width="fill",
            {
              CircleImageView,
              src="https://i.loli.net/2019/07/22/5d348cef4e08f90451.png",
              layout_width="13%h",
              layout_height="fill",
            },
            {
              LinearLayout,
              orientation="vertical",
              layout_height="fill",
              gravity="center|left",
              {
                TextView,
                text="免费空间",
                textSize="18sp",
                textColor=0xff444444,
              },
            },
          },
          {
            CircleImageView,
            layout_width="7%h",
            layout_height="fill",
            layout_alignParentRight=true,
          },
        },
        {
          TextView,
          textColor=0xff444444,
          textSize="15sp",
          padding="4%w",
          text=[[免费空间 free.3v.do 国内最好的免费空间提供商,为您提供100M永久免费ASP空间,免费美国空间申请,支持HTML,ASP,FTP上传,高速稳定,实时生效,无需等待,免备案]],
        },
        {
          LinearLayout,
          orientation="horizontal",
          layout_height="4%h",
          paddingRight="4%w",
          layout_gravity="right|center",
          {
            TextView,
            gravity="center",
            text="访问网站",
            textColor=returntheme(),
            textSize="14sp",
            id="bt3";
            paddingRight="1%w",
            layout_height="fill",
          },
          {
            ImageView,
            src="image/left.png",
            layout_height="fill",
            layout_width="4%h",
            colorFilter=returntheme(),
            padding="0.75%w",
            rotation=180,
          },
        },
      },
      {
        TextView,
        text="其他感谢",
        padding="4%w",
      },
      {
        LinearLayout,
        orientation="vertical",
        layout_height="wrap",
        layout_width="fill",
        onClick=function ()
          浏览器打开网页("https://www.lanzous.com/b397571")
        end,
        foreground=转波纹色(0xcb5B5B5B),
        paddingBottom="2%w",
        {
          RelativeLayout,
          padding="4%w",
          paddingLeft=0,
          layout_height="13%h",
          {
            LinearLayout,
            orientation="horizontal",
            layout_height="13%h",
            layout_width="fill",
            {
              CircleImageView,
              src="https://i.loli.net/2019/07/22/5d34901b036ce49658.png",
              layout_width="13%h",
              layout_height="fill",
            },
            {
              LinearLayout,
              orientation="vertical",
              layout_height="fill",
              gravity="center|left",
              {
                TextView,
                text="木有仙工作室",
                textSize="18sp",
                textColor=0xff444444,
              },
            },
          },
          {
            CircleImageView,
            layout_width="7%h",
            layout_height="fill",
            layout_alignParentRight=true,
          },
        },
        {
          TextView,
          textColor=0xff444444,
          textSize="15sp",
          padding="4%w",
          text=[[木有仙工作室,其代表作Toolbox是一款轻快便捷的工具箱软件]],
        },
        {
          LinearLayout,
          orientation="horizontal",
          layout_height="4%h",
          paddingRight="4%w",
          layout_gravity="right|center",
          {
            TextView,
            gravity="center",
            text="下载该APP",
            textColor=returntheme(),
            textSize="14sp",
            id="bt4";
            paddingRight="1%w",
            layout_height="fill",
          },
          {
            ImageView,
            src="image/left.png",
            layout_height="fill",
            layout_width="4%h",
            colorFilter=returntheme(),
            padding="0.75%w",
            rotation=180,
          },
        },
      },
    },
    {
      LinearLayout,
      orientation="vertical",
      layout_height="wrap",
      layout_width="fill",
      onClick=function ()
        浏览器打开网页("https://www.lanzous.com/b397571")
      end,
      foreground=转波纹色(0xcb5B5B5B),
      paddingBottom="2%w",
      {
        RelativeLayout,
        padding="4%w",
        paddingLeft=0,
        layout_height="13%h",
        {
          LinearLayout,
          orientation="horizontal",
          layout_height="13%h",
          layout_width="fill",
          {
            CircleImageView,
            src="https://i.loli.net/2019/07/22/5d34901b036ce49658.png",
            layout_width="13%h",
            layout_height="fill",
          },
          {
            LinearLayout,
            orientation="vertical",
            layout_height="fill",
            gravity="center|left",
            {
              TextView,
              text="木有仙工作室",
              textSize="18sp",
              textColor=0xff444444,
            },
          },
        },
        {
          CircleImageView,
          layout_width="7%h",
          layout_height="fill",
          layout_alignParentRight=true,
        },
      },
    },
    {
      LinearLayout,
      orientation="vertical",
      layout_height="wrap",
      layout_width="fill",
      onClick=function ()
        浏览器打开网页("https://www.lanzous.com/b397571")
      end,
      foreground=转波纹色(0xcb5B5B5B),
      paddingBottom="2%w",
      {
        RelativeLayout,
        padding="4%w",
        paddingLeft=0,
        layout_height="13%h",
        {
          LinearLayout,
          orientation="horizontal",
          layout_height="13%h",
          layout_width="fill",
          {
            CircleImageView,
            src="https://i.loli.net/2019/07/22/5d34901b036ce49658.png",
            layout_width="13%h",
            layout_height="fill",
          },
          {
            LinearLayout,
            orientation="vertical",
            layout_height="fill",
            gravity="center|left",
            {
              TextView,
              text="木有仙工作室",
              textSize="18sp",
              textColor=0xff444444,
            },
          },
        },
        {
          CircleImageView,
          layout_width="7%h",
          layout_height="fill",
          layout_alignParentRight=true,
        },
      },
    },

  },
}))



function onPause()
  collectgarbage("collect")
end


bt1.getPaint().setFakeBoldText(true)
bt2.getPaint().setFakeBoldText(true)
bt3.getPaint().setFakeBoldText(true)
bt4.getPaint().setFakeBoldText(true)